### ISSUE TITLE
A Great Start! Congratulations but a few things to look into.

### ISSUE THREAD

**Issue by perkinsjr** [desaijay315/react-graphql-apollo-pagination#1]
Hey,

Great start to my challenge, here are some things that need tweaking:

1. add some margin to the buttons ml={4} should do it. to space them.
2. The pagination breaks if you search for a new Character (it returns the old state from the previous pagination)

Overall very impressed with your changes!

**Comment by desaijay315** [comment]
Thank you so much, James, for taking your time out and reviewing the codebase...

**Comment by desaijay315** [comment]
Hey @perkinsjr , Both issues are now handled in a particular way, as it seems that for the characters, both page, and filter params, if wrong, this give 404 not found error, thought i thing this change should be fine.

**Comment by desaijay315** [comment]
Hey @perkinsjr , I do want to add caching with apollo client and it seems apollo does provide method, to set and get data from the cache.

Current implementation hits the API each time on click, opening new issue for the same. Let me know your thought on this
